#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose
  - mysql-client

# Start the Docker service
runcmd:
  - systemctl start docker
  - systemctl enable docker

# Add the 'ubuntu' user to the 'docker' group
runcmd:
  - sudo usermod -aG docker ubuntu

# Create directory for Docker Compose file and WordPress data
runcmd:
  - mkdir /opt/wordpress
  - chown ubuntu:ubuntu /opt/wordpress
  - mkdir /var/www/html
  - chown ubuntu:ubuntu /var/www/html

# Write Docker Compose file
write_files:
  - path: /opt/wordpress/docker-compose.yml
    content: |
      version: '3'
      services:
        wordpress:
          image: wordpress
          ports:
            - 80:80
          volumes:
            - /var/www/html:/var/www/html
          environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
          restart: always

# Run Docker Compose
runcmd:
  - cd /opt/wordpress
  - docker-compose up -d
